// Generated by gencpp from file ros_package4/Sum.msg
// DO NOT EDIT!


#ifndef ROS_PACKAGE4_MESSAGE_SUM_H
#define ROS_PACKAGE4_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <ros_package4/SumRequest.h>
#include <ros_package4/SumResponse.h>


namespace ros_package4
{

struct Sum
{

typedef SumRequest Request;
typedef SumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sum
} // namespace ros_package4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_package4::Sum > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::ros_package4::Sum&) { return value(); }
};

template<>
struct DataType< ::ros_package4::Sum > {
  static const char* value()
  {
    return "ros_package4/Sum";
  }

  static const char* value(const ::ros_package4::Sum&) { return value(); }
};


// service_traits::MD5Sum< ::ros_package4::SumRequest> should match
// service_traits::MD5Sum< ::ros_package4::Sum >
template<>
struct MD5Sum< ::ros_package4::SumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_package4::Sum >::value();
  }
  static const char* value(const ::ros_package4::SumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_package4::SumRequest> should match
// service_traits::DataType< ::ros_package4::Sum >
template<>
struct DataType< ::ros_package4::SumRequest>
{
  static const char* value()
  {
    return DataType< ::ros_package4::Sum >::value();
  }
  static const char* value(const ::ros_package4::SumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_package4::SumResponse> should match
// service_traits::MD5Sum< ::ros_package4::Sum >
template<>
struct MD5Sum< ::ros_package4::SumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_package4::Sum >::value();
  }
  static const char* value(const ::ros_package4::SumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_package4::SumResponse> should match
// service_traits::DataType< ::ros_package4::Sum >
template<>
struct DataType< ::ros_package4::SumResponse>
{
  static const char* value()
  {
    return DataType< ::ros_package4::Sum >::value();
  }
  static const char* value(const ::ros_package4::SumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_PACKAGE4_MESSAGE_SUM_H
