// Generated by gencpp from file beginner_tutorials/Sum.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SUM_H
#define BEGINNER_TUTORIALS_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <beginner_tutorials/SumRequest.h>
#include <beginner_tutorials/SumResponse.h>


namespace beginner_tutorials
{

struct Sum
{

typedef SumRequest Request;
typedef SumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sum
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Sum > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tutorials::Sum&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Sum > {
  static const char* value()
  {
    return "beginner_tutorials/Sum";
  }

  static const char* value(const ::beginner_tutorials::Sum&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::SumRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::Sum >
template<>
struct MD5Sum< ::beginner_tutorials::SumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Sum >::value();
  }
  static const char* value(const ::beginner_tutorials::SumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SumRequest> should match
// service_traits::DataType< ::beginner_tutorials::Sum >
template<>
struct DataType< ::beginner_tutorials::SumRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Sum >::value();
  }
  static const char* value(const ::beginner_tutorials::SumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::SumResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::Sum >
template<>
struct MD5Sum< ::beginner_tutorials::SumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Sum >::value();
  }
  static const char* value(const ::beginner_tutorials::SumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SumResponse> should match
// service_traits::DataType< ::beginner_tutorials::Sum >
template<>
struct DataType< ::beginner_tutorials::SumResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Sum >::value();
  }
  static const char* value(const ::beginner_tutorials::SumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SUM_H
